stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://jancarlodelmoro.netlify.app
  only:
    - p1-web-dev-portfolio
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
